### ISSUE TITLE
Standardising on language

### ISSUE THREAD

**Issue by Fastidious** [ndavd/agevault#1]
Hey, love `agevault`. I noticed that directory, and vault, and locked, and encrypted, are used. Will you agree to set some consistency? For example:

```
agevault v1.1.0
lock/unlock directory with passphrase-protected identity file
usage: agevault [directory-name] lock|unlock|keygen
```

Notice `directory-name` instead of `vault-name`.

And if:

```
directory-name LOCKED with...
```

Then after unlocking it should be:

```
directory-name UNLOCKED
```

What do you think?

**Comment by ndavd** [comment]
Hi, I'm glad you enjoy `agevault`.
Thanks for the issue, that's a great suggestion :)
